---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: grpc-web-front
  name: grpc-web-front
spec:
  replicas: 2
  selector:
    matchLabels:
      run: grpc-web-front
  strategy: {}
  template:
    metadata:
      labels:
        run: grpc-web-front
    spec:
      containers:
      - image: asia.gcr.io/agdc-k8s/grpc-web-front:latest
        name: grpc-web-front
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: grpc-web-front-config
        ports:
        - containerPort: 3000        
status: {}
