---
apiVersion: v1
kind: Service
metadata:
  name: grpc-web-front
spec:
  type: LoadBalancer
  loadBalancerIP: 35.221.114.196
  ports:
  - name: front-port
    port: 3000
    targetPort: 3000
  selector:
    run: grpc-web-front
