---
apiVersion: skaffold/v1alpha2
kind: Config
build:
  local: { skipPush: true }
  artifacts:
  - imageName: asia.gcr.io/agdc-k8s/grpc-web-front
deploy:
  kubectl:
    manifests:
      - k8s/local/*
