---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: grpc-web-front
  name: grpc-web-front
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grpc-web-front
  strategy: {}
  template:
    metadata:
      labels:
        run: grpc-web-front
    spec:
      containers:
      - image: asia.gcr.io/agdc-k8s/grpc-web-front:7df55f607901950b09ec735968ba62d220ede814
        name: grpc-web-front
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          timeoutSeconds: 60
          initialDelaySeconds: 30
          periodSeconds: 30
        envFrom:
        - configMapRef:
            name: grpc-web-front-config
        ports:
        - containerPort: 3000        
status: {}
