---
version: 2
jobs:
  test:
    docker:
      - image: node:10.5.0-alpine
    working_directory: ~/grpc-web-front
    steps:
      - checkout
      - setup_remote_docker: {docker_layer_caching: true}
      - run:
          command: echo "test"
  build:
    docker:
      - image: node:10.5.0-alpine
    working_directory: ~/grpc-web-front
    steps:
      - checkout
      - setup_remote_docker: {docker_layer_caching: true}
      - run:
          command: apk add --no-cache ca-certificates
      - run:
          command: npm i && npm run _build
      - persist_to_workspace:
          root: .
          paths:
            - .
  package:
    docker:
      - image: errordeveloper/skaffold:66cc263ef18f107adce245b8fc622a8ea46385f2
    working_directory: ~/grpc-web-front
    steps:
      - checkout
      - setup_remote_docker: {docker_layer_caching: true}
      - attach_workspace:
          at: .
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: |
            if [[ -z "${CIRCLE_PULL_REQUEST}" ]] ; then
              skaffold build --profile=prd
            else
              echo "Do not run skaffold"
            fi

workflows:
  version: 2
  test-and-build-and-package:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - package:
          requires:
            - build
          filters:
            branches:
              only: master