---
apiVersion: v1
kind: Service
metadata:
  name: grpc-web-front
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"fe":"HTTP2"}'
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    run: grpc-web-front
